- name: Copy conf
  copy:
    src: httpd.conf
    dest: /home/admin/
    mode: '0644'

- name: Launch Apache HTTPD container
  community.docker.docker_container:
    name: my_proxy
    image: antoinecmbld/http-server:latest
    ports:
      - "80:80"
    volumes:
      - /home/admin/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - name: my_app_network
    restart_policy: always
