- name: Copy .env file
  copy:
    src: .env
    dest: /home/admin/db.env

- name: Launch PostgreSQL container
  community.docker.docker_container:
    name: db
    image: antoinecmbld/database:latest
    env_file: /home/admin/db.env
    networks:
      - name: my_app_network
    restart_policy: always
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "psw"